### ISSUE TITLE
Update Docker images using github actions

### ISSUE THREAD

**Issue by APaganini** [fireshape/fireshape#73]

**Comment by APaganini** [comment]
Jack suggests:

I guess the starting point would be the (relevant sections of the) firedrake build.yml file: https://github.com/firedrakeproject/firedrake/blob/master/.github/workflows/build.yml
```

docker_env:
    name: "Build Docker environment container"
    # The type of runner that the job will run on
    needs: build
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push firedrake-env
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker/Dockerfile.env
          tags: firedrakeproject/firedrake-env:latest
```

The most relevant bits (I think) are:

- `needs: build `this is the step that the docker build depends on (in this case, we only build the Docker image if tests pass)
- `if: ${{ github.ref == 'refs/heads/master' }}` only build docker images on push to `master `branch
- `${{ secrets.DOCKERHUB_USER }} & ${{ secrets.DOCKERHUB_TOKEN }}` these are just the username and password for the docker account which are added to the github secrets thing in the repo settings (or better yet, organisation settings if you want to share across multiple repos)
